version: '3.8'

networks:
  fraud-detection-net:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - fraud-detection-net

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - fraud-detection-net

  hdfs-namenode:
    build:
      context: ./hdfs
      dockerfile: Dockerfile.namenode
    environment:
      - CLUSTER_NAME=fraud-detection
    ports:
      - "9870:9870"  # HDFS Namenode Web UI
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    networks:
      - fraud-detection-net

  hdfs-datanode:
    build:
      context: ./hdfs
      dockerfile: Dockerfile.datanode
    environment:
      - CLUSTER_NAME=fraud-detection
    ports:
      - "9864:9864"  # HDFS Datanode Web UI
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    depends_on:
      - hdfs-namenode
    networks:
      - fraud-detection-net

  spark:
    build: ./spark
    ports:
      - "4040:4040"  # Spark UI
      - "7077:7077"  # Spark Master
    environment:
      - SPARK_MODE=master
    depends_on:
      - kafka
      - hdfs-namenode
    networks:
      - fraud-detection-net

  nifi:
    build: ./nifi
    ports:
      - "8080:8080"  # NiFi Web UI
    depends_on:
      - hdfs-namenode
      - hbase
    networks:
      - fraud-detection-net

  hbase:
    build: ./hbase
    ports:
      - "16010:16010"  # HBase Master UI
      - "9090:9090"    # REST API
    environment:
      - HBASE_MANAGES_ZK=true
    networks:
      - fraud-detection-net

  atm-simulator:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./atm-simulator:/app
    command: ["python", "atm_producer.py"]
    depends_on:
      - kafka
    networks:
      - fraud-detection-net

volumes:
  hdfs_namenode:
  hdfs_datanode:
